use sample
SELECT * FROM tblEmployee

CREATE FUNCTION fn_Test(@Gender nvarchar(20))
RETURNS TABLE
AS
RETURN (SELECT * FROM tblEmployee WHERE GENDER = @Gender)

select * from fn_Test('Male')

drop FUNCTION fn_Test

CREATE FUNCTION fn_Test(@Gender int)
RETURNS @Table TABLE(NAME nvarchar(20), GENDER nvarchar(20))
AS
BEGIN
	INSERT INTO @Table
	SELECT NAME, GENDER FROM tblEmployee
	RETURN
END

CREATE FUNCTION fn_Test(@gender nvarchar(20))
RETURNS @TABLE TABLE(NAME nvarchar(20), Gender nvarchar(20))
AS
BEGIN
	INSERT INTO @TABLE
	SELECT NAME, GENDER FROM tblEmployee WHERE GENDER = @Gender
	RETURN
END


SELECT * FROM fn_Test('Male')
UPDATE fn_Test('male') SET NAME = 'Tommy' WHERE ID = 1

SELECT GETDATE()

drop FUNCTION fn_Test

ALTER FUNCTION fn_Test(@gender int)
returns @table table(name nvarchar(20), gender nvarchar(20))
with SCHEMABINDING
as
begin
	insert into @table
	select name, gender from DBO.tblEmployee
	return
end

sp_helptext fn_test

DROP TABLE tblEmployee

DROP TABLE INDEX_TEST2
GO

CREATE TABLE INDEX_TEST2
(
ID INT,
NAME NVARCHAR(20),
GENDER NVARCHAR(20)
)

INSERT INTO INDEX_TEST2 VALUES(3,'JOHN', 'MALE')
INSERT INTO INDEX_TEST2 VALUES(5,'MIKE', 'MALE')
INSERT INTO INDEX_TEST2 VALUES(2,'AMY', 'FEMALE')

SELECT * FROM INDEX_TEST2

CREATE CLUSTERED INDEX IX_INDEX_TEST2_NAME_GENDER
ON INDEX_TEST2 (NAME ASC, GENDER DESC)


SELECT * FROM INDEX_TEST2

SP_HELPINDEX INDEX_TEST2

DROP INDEX INDEX_TEXT2.IX_INDEX_TEST2_NAME_GENDER

ALTER TABLE INDEX_TEST2
ADD CONSTRAINT UQ_INDEX_TEST2_ID
UNIQUE(ID)

SP_HELPINDEX INDEX_TEST2
DROP INDEX INDEX_TEXT2.UQ_INDEX_TEST2_ID

ALTER UNIQUE INDEX IX_INDEX_TEST2_ID
ON INDEX_TEST2 (ID, DESC)

SELECT * FROM INDEX_TEST2

CREATE VIEW vWTest
AS
SELECT A.NAME, A.GENDER, B.DEPARTMENTNAME FROM TBLEMPLOYEE A
JOIN TBLDEPARTMENT B
ON A.DEPARTMENTID=B.ID

SELECT * FROM vWTest WHERE DEPARTMENTNAME = 'IT'

DROP TABLE TEST1
GO
CREATE TABLE TEST1
(
ID INT IDENTITY(1,1) PRIMARY KEY,
DEPARTMENTID INT,
NAME NVARCHAR(20)
)
GO
INSERT INTO TEST1 VALUES(1,'JOHN')
INSERT INTO TEST1 VALUES(1,'MARY')
INSERT INTO TEST1 VALUES(2,'TOM')
INSERT INTO TEST1 VALUES(2,'MAY')
GO
DROP TABLE TEST2
GO
CREATE TABLE TEST2
(
ID INT IDENTITY(1,1) PRIMARY KEY,
DEPARTMENTNAME NVARCHAR(20)
)
GO
INSERT INTO TEST2 VALUES('IT')
INSERT INTO TEST2 VALUES('HR')
GO
DROP VIEW VIEWTEST
GO
CREATE VIEW VIEWTEST
AS
SELECT A.NAME, A.DEPARTMENTID, B.DEPARTMENTNAME FROM TEST1 A
JOIN TEST2 B
ON A.DEPARTMENTID=B.ID
GO
SELECT * FROM VIEWTEST


SELECT * FROM TEST1
SELECT * FROM TEST2
UPDATE VIEWTEST SET DEPARTMENTNAME = 'F' WHERE NAME = 'JOHN'