/*
Advantage of Stored Procedures
1. Excecution plan retention and resuability --Execution Plan: The plan to run the query generated by SQL. They will be cached by SQL for futher reusing¡£
	If a query is executed normally, the change of parameter will reset a new execution plan, which is time consuming
	eg. Select Name from tblEmployee Where Id = 1 will generate a execution plan
	however, if I slightly change the parameter:
		Select Name from tblEmployee Where Id = 2 will reset a new execution plan
	even Select Name from tblEmployee Where Id =		1 will regenerate a execution plan because of the extra space.
	Using a SQ is a better way because it will cache the query
2. Reduce Network Traffic
	It means that you don't need to type too many words. If use procedure, it will just a line and it will run on the server rather than using the network traffic
3. Code resusability and better maintainability
4. Better security
	Grant procedure right to a user but not the whole table
5. Avoid SQL injection attack
*/

use sample
Create Proc spGetNameById
@Id int
As
Begin
	Select * from tblEmployee where Id = @id
End

Exec spGetNameById 1
